apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lxormzqp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-lxormzqp:4bb48e168107eefdcff1c630c5dc84e062a7bd8a@sha256:4fc9c25eb186223555d387ee0ec133ef23c158a14d4db2bdb6bd731af5e4fb87
          name: container-image
